#include "nes_decoder.h"


NES_INSTRUCTION nes_instructions[256] = {
	{"BRK", AM_impl, 7},
	{"ORA", AM_X_ind, 6},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"ORA", AM_zpg, 3},
	{"ASL", AM_zpg, 5},
	{NULL , AM_impl, -1},
	{"PHP", AM_impl, 3},
	{"ORA", AM_hash, 2},
	{"ASL", AM_A, 2},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"ORA", AM_abs, 4},
	{"ASL", AM_abs, 6},
	{NULL , AM_impl, -1},
	{"BPL", AM_rel, 2},
	{"ORA", AM_ind_Y, 5},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"ORA", AM_zpg_X, 4},
	{"ASL", AM_zpg_X, 6},
	{NULL , AM_impl, -1},
	{"CLC", AM_impl, 2},
	{"ORA", AM_abs_Y, 4},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"ORA", AM_abs_X, 4},
	{"ASL", AM_abs_X, 7},
	{NULL , AM_impl, -1},
	{"JSR", AM_abs, 6},
	{"AND", AM_X_ind, 6},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"BIT", AM_zpg, 3},
	{"AND", AM_zpg, 3},
	{"ROL", AM_zpg, 5},
	{NULL , AM_impl, -1},
	{"PLP", AM_impl, 4},
	{"AND", AM_hash, 2},
	{"ROL", AM_A, 2},
	{NULL , AM_impl, -1},
	{"BIT", AM_abs, 4},
	{"AND", AM_abs, 4},
	{"ROL", AM_abs, 6},
	{NULL , AM_impl, -1},
	{"BMI", AM_rel, 2},
	{"AND", AM_ind_Y, 5},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"AND", AM_zpg_X, 4},
	{"ROL", AM_zpg_X, 6},
	{NULL , AM_impl, -1},
	{"SEC", AM_impl, 2},
	{"AND", AM_abs_Y, 4},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"AND", AM_abs_X, 4},
	{"ROL", AM_abs_X, 7},
	{NULL , AM_impl, -1},
	{"RTI", AM_impl, 6},
	{"EOR", AM_X_ind, 6},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"EOR", AM_zpg, 3},
	{"LSR", AM_zpg, 5},
	{NULL , AM_impl, -1},
	{"PHA", AM_impl, 3},
	{"EOR", AM_hash, 2},
	{"LSR", AM_A, 2},
	{NULL , AM_impl, -1},
	{"JMP", AM_abs, 3},
	{"EOR", AM_abs, 4},
	{"LSR", AM_abs, 6},
	{NULL , AM_impl, -1},
	{"BVC", AM_rel, 2},
	{"EOR", AM_ind_Y, 5},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"EOR", AM_zpg_X, 4},
	{"LSR", AM_zpg_X, 6},
	{NULL , AM_impl, -1},
	{"CLI", AM_impl, 2},
	{"EOR", AM_abs_Y, 4},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"EOR", AM_abs_X, 4},
	{"LSR", AM_abs_X, 7},
	{NULL , AM_impl, -1},
	{"RTS", AM_impl, 6},
	{"ADC", AM_X_ind, 6},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"ADC", AM_zpg, 3},
	{"ROR", AM_zpg, 5},
	{NULL , AM_impl, -1},
	{"PLA", AM_impl, 4},
	{"ADC", AM_hash, 2},
	{"ROR", AM_A, 2},
	{NULL , AM_impl, -1},
	{"JMP", AM_ind, 5},
	{"ADC", AM_abs, 4},
	{"ROR", AM_abs, 6},
	{NULL , AM_impl, -1},
	{"BVS", AM_rel, 2},
	{"ADC", AM_ind_Y, 5},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"ADC", AM_zpg_X, 4},
	{"ROR", AM_zpg_X, 6},
	{NULL , AM_impl, -1},
	{"SEI", AM_impl, 2},
	{"ADC", AM_abs_Y, 4},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"ADC", AM_abs_X, 4},
	{"ROR", AM_abs_X, 7},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"STA", AM_X_ind, 6},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"STY", AM_zpg, 3},
	{"STA", AM_zpg, 3},
	{"STX", AM_zpg, 3},
	{NULL , AM_impl, -1},
	{"DEY", AM_impl, 2},
	{NULL , AM_impl, -1},
	{"TXA", AM_impl, 2},
	{NULL , AM_impl, -1},
	{"STY", AM_abs, 4},
	{"STA", AM_abs, 4},
	{"STX", AM_abs, 4},
	{NULL , AM_impl, -1},
	{"BCC", AM_rel, 2},
	{"STA", AM_ind_Y, 6},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"STY", AM_zpg_X, 4},
	{"STA", AM_zpg_X, 4},
	{"STX", AM_zpg_Y, 4},
	{NULL , AM_impl, -1},
	{"TYA", AM_impl, 2},
	{"STA", AM_abs_Y, 5},
	{"TXS", AM_impl, 2},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"STA", AM_abs_X, 5},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"LDY", AM_hash, 2},
	{"LDA", AM_X_ind, 6},
	{"LDX", AM_hash, 2},
	{NULL , AM_impl, -1},
	{"LDY", AM_zpg, 3},
	{"LDA", AM_zpg, 3},
	{"LDX", AM_zpg, 3},
	{NULL , AM_impl, -1},
	{"TAY", AM_impl, 2},
	{"LDA", AM_hash, 2},
	{"TAX", AM_impl, 2},
	{NULL , AM_impl, -1},
	{"LDY", AM_abs, 4},
	{"LDA", AM_abs, 4},
	{"LDX", AM_abs, 4},
	{NULL , AM_impl, -1},
	{"BCS", AM_rel, 2},
	{"LDA", AM_ind_Y, 5},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"LDY", AM_zpg_X, 4},
	{"LDA", AM_zpg_X, 4},
	{"LDX", AM_zpg_Y, 4},
	{NULL , AM_impl, -1},
	{"CLV", AM_impl, 2},
	{"LDA", AM_abs_Y, 4},
	{"TSX", AM_impl, 2},
	{NULL , AM_impl, -1},
	{"LDY", AM_abs_X, 4},
	{"LDA", AM_abs_X, 4},
	{"LDX", AM_abs_Y, 4},
	{NULL , AM_impl, -1},
	{"CPY", AM_hash, 2},
	{"CMP", AM_X_ind, 6},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"CPY", AM_zpg, 3},
	{"CMP", AM_zpg, 3},
	{"DEC", AM_zpg, 5},
	{NULL , AM_impl, -1},
	{"INY", AM_impl, 2},
	{"CMP", AM_hash, 2},
	{"DEX", AM_impl, 2},
	{NULL , AM_impl, -1},
	{"CPY", AM_abs, 4},
	{"CMP", AM_abs, 4},
	{"DEC", AM_abs, 6},
	{NULL , AM_impl, -1},
	{"BNE", AM_rel, 2},
	{"CMP", AM_ind_Y, 5},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"CMP", AM_zpg_X, 4},
	{"DEC", AM_zpg_X, 6},
	{NULL , AM_impl, -1},
	{"CLD", AM_impl, 2},
	{"CMP", AM_abs_Y, 4},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"CMP", AM_abs_X, 4},
	{"DEC", AM_abs_X, 7},
	{NULL , AM_impl, -1},
	{"CPX", AM_hash, 2},
	{"SBC", AM_X_ind, 6},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"CPX", AM_zpg, 3},
	{"SBC", AM_zpg, 3},
	{"INC", AM_zpg, 5},
	{NULL , AM_impl, -1},
	{"INX", AM_impl, 2},
	{"SBC", AM_hash, 2},
	{"NOP", AM_impl, 2},
	{NULL , AM_impl, -1},
	{"CPX", AM_abs, 4},
	{"SBC", AM_abs, 4},
	{"INC", AM_abs, 6},
	{NULL , AM_impl, -1},
	{"BEQ", AM_rel, 2},
	{"SBC", AM_ind_Y, 5},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"SBC", AM_zpg_X, 4},
	{"INC", AM_zpg_X, 6},
	{NULL , AM_impl, -1},
	{"SED", AM_impl, 2},
	{"SBC", AM_abs_Y, 4},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{NULL , AM_impl, -1},
	{"SBC", AM_abs_X, 4},
	{"INC", AM_abs_X, 7},
	{NULL , AM_impl, -1}
};

int BB_END_OPCODES_INTERNAL[] = {0x4C, 0x6C, 0x60};

int *BB_END_OPCODES = BB_END_OPCODES_INTERNAL;
int BB_END_OPCODES_COUNT = sizeof(BB_END_OPCODES_INTERNAL)/sizeof(*BB_END_OPCODES_INTERNAL);
